# Generated by Django 6.0.5 on 2026-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=55)),
                ('phone_no', models.BigIntegerField()),
                ('address', models.CharField(default='unknown', max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('emp_type', models.CharField(max_length=100)),
            ],
        ),
    ]
